UPDATE `seguimientos` SET `seguimiento` = 'Dado de alta (Por parte del paciente)' WHERE `seguimientos`.`id` = 4;
ALTER TABLE `seguimientos` ADD `icono` VARCHAR(10) NOT NULL AFTER `color`;
UPDATE `seguimientos` SET `icono` = '⚪' WHERE `seguimientos`.`id` = 1;
UPDATE `seguimientos` SET `icono` = '🔴' WHERE `seguimientos`.`id` = 2;
UPDATE `seguimientos` SET `icono` = '🟡' WHERE `seguimientos`.`id` = 3;
UPDATE `seguimientos` SET `icono` = '🟠' WHERE `seguimientos`.`id` = 6;
UPDATE `seguimientos` SET `icono` = '🟢' WHERE `seguimientos`.`id` in (4,7);
UPDATE `seguimientos` SET `icono` = '⚫' WHERE `seguimientos`.`id` = 5;
UPDATE `seguimientos` SET `color` = 'text-body' WHERE `seguimientos`.`id` = 5;
INSERT INTO `seguimientos` (`id`, `seguimiento`, `color`, `icono`) VALUES (NULL, 'Contestado', 'text-success', '🟢');
CREATE TABLE `deudas_pacientes` ( `id` int(11) NOT NULL AUTO_INCREMENT, `registro` datetime DEFAULT current_timestamp(), `patient_id` int(11) NOT NULL, `user_id` int(11) NOT NULL, `idSeguimiento` int(11) NOT NULL, `observaciones` text CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL, `activo` int(11) NOT NULL DEFAULT 1, PRIMARY KEY (`id`) ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `seguimientos` (`id`, `seguimiento`, `color`, `icono`) VALUES (NULL, 'Deuda pendiente', 'text-muted', '⚪');
INSERT INTO `seguimientos` (`id`, `seguimiento`, `color`, `icono`) VALUES (NULL, 'Deuda cobrada', 'text-success', '🟢');
INSERT INTO `seguimientos` (`id`, `seguimiento`, `color`, `icono`) VALUES (NULL, 'Deuda perdida', 'text-danger', '🔴');
INSERT INTO `seguimientos` (`id`, `seguimiento`, `color`, `icono`) VALUES (NULL, 'Deuda con plazo extendido', 'text-warning', '🟡');
ALTER TABLE `deudas_pacientes` ADD `idDeuda` INT NOT NULL AFTER `registro`;
ALTER TABLE `deudas` CHANGE `estado` `estado` INT(11) NULL DEFAULT '1' COMMENT '1=deuda, 2=cobrado, 3=perdida, 4=plazo ext';
UPDATE `extra_payments` SET `moneda`=12 where moneda = 3;
UPDATE `payment_method` SET `tipo` = 'Yape' WHERE `payment_method`.`id` = 4;
UPDATE `payments` SET `payment_method`=1 where `payment_method`='Efectivo';
UPDATE `payments` SET `payment_method`=2 where `payment_method`='Depósito';
UPDATE `payments` SET `payment_method`=11 where `payment_method`='Izipay';
UPDATE `payments` SET `payment_method`=4 where `payment_method`='Yape';
UPDATE `payments` SET `payment_method`=1 where `payment_method`='null';
UPDATE `payments` SET `payment_method`=12 where `payment_method`=3;
ALTER TABLE `patients` ADD `vivo` INT NULL DEFAULT '1' AFTER `seguimiento`;
UPDATE `patients` SET `phone`='' where `phone` is null;
UPDATE `patients` SET `phone`='' where `phone` = 'null';
UPDATE `patients` SET `email`='' where `email` is null;
UPDATE `patients` SET `email`='' where `email` = 'null';
