INSERT INTO `precios` (`id`, `descripcion`, `nuevos`, `continuos`, `idClasificacion`, `activo`) VALUES (NULL, 'Membresía Clínica de día', '600', '600', '4', '1');
UPDATE `precios` SET `activo` = '1' WHERE `precios`.`id` = 15;
CREATE TABLE `consultorio`.`deudas` (`id` INT NOT NULL AUTO_INCREMENT , `patient_id` INT NOT NULL , `motivo` INT NOT NULL , `user_id` INT NOT NULL , `registro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP , `fecha` DATE NOT NULL , `monto` FLOAT NOT NULL , `activo` INT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `consultorio`.`membresias` (`id` INT NOT NULL AUTO_INCREMENT , `patient_id` INT NOT NULL , `inicio` INT NOT NULL , `fin` INT NOT NULL , `tipo` INT NOT NULL COMMENT '15=kurame, 28=clinica' , `user_id` INT NOT NULL , `cuotas` INT NOT NULL , `monto` FLOAT NOT NULL , `activo` INT NULL DEFAULT '1' , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `membresias` CHANGE `inicio` `inicio` INT(11) NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `membresias` CHANGE `fin` `fin` DATE NOT NULL;
ALTER TABLE `membresias` CHANGE `inicio` `inicio` DATE NULL DEFAULT CURRENT_TIMESTAMP;
CREATE TABLE `consultorio`.`tipo_pagos` (`id` INT NOT NULL AUTO_INCREMENT , `descripcion` INT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `tipo_pagos` CHANGE `descripcion` `descripcion` VARCHAR(250) NOT NULL;
ALTER TABLE `extra_payments` CHANGE `type` `type` TINYINT(4) NULL DEFAULT NULL COMMENT 'tabla tipo_pagos';
INSERT INTO `tipo_pagos` (`id`, `descripcion`) VALUES ('0', 'Certificado');
UPDATE `tipo_pagos` SET `id`=0 WHERE 1;
INSERT INTO `tipo_pagos` (`id`, `descripcion`) VALUES ('1', 'Paquete de membresía'), ('2', 'Paquete kurame'), ('3', 'Informe'), ('4', 'Otros'), ('5', 'Cobro de cita'), ('6', 'Salida de dinero'), ('7', 'Pago de membresía');
ALTER TABLE `deudas` CHANGE `activo` `activo` INT(11) NULL DEFAULT '1';
ALTER TABLE `deudas` CHANGE `motivo` `motivo` VARCHAR(250) NOT NULL;
ALTER TABLE `deudas` ADD `idMembresia` INT NULL DEFAULT NULL AFTER `activo`;
ALTER TABLE `deudas` ADD `idActualiza` INT NULL DEFAULT NULL AFTER `idMembresia`;
ALTER TABLE `deudas` ADD `fechaActualiza` DATE NULL DEFAULT NULL AFTER `idActualiza`;
ALTER TABLE `deudas` ADD `estado` INT NULL DEFAULT '1' COMMENT '1=deuda, 2=cobrado, 3=perdida' AFTER `monto`;